name: Deploy CDK Stack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Install dependencies
      run: npm ci

    - name: CDK Synth
      run: npx cdk synth
      
    - name: CDK Diff
      run: npx cdk diff
      # This will show changes before deployment
      
    - name: CDK Deploy
      if: github.ref == 'refs/heads/main' # Only deploy on main branch
      run: npx cdk deploy --require-approval never